services:
  - type: web
    name: traceimei-backend
    env: python
    region: frankfurt
    plan: free
    runtime: python
    pythonVersion: "3.11.8"
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
